Updates bennu maven plugin jdk version to 11
qub-it/bennu pull request #15
Opened 2023-12-06 18:10 UTC by joaofreitas-qubit

Relates with: #qubIT-Omnis-4736

2023-12-11 13:59 UTC, joaojtmarques-qubit commented
Bennu does not have Release Notes. Should we not add them?

2023-12-12 12:14 UTC, pabrantes commented
@joaojtmarques-qubit 

> Bennu does not have Release Notes. Should we not add them?

Yep, in the case of bennu we skip the release notes procedure.

2023-12-12 12:16 UTC, pabrantes requested changes

2023-12-12 12:16 UTC, pabrantes commented on pom.xml
> -            <dependency>
@joaofreitas-qubit why are we removing the dependency itself and not just the version?

2023-12-13 11:31 UTC, merged